### PR TITLE
:penguin: UPDATE dist to bionic

### PR DESCRIPTION
**Pull request by tkoyama010**
Hi all. this is a PR which is same to this [PR](https://github.com/sphinx-doc/sphinx-doc-translations/pull/3).

Thank you for reading.

### CODE REVIEW

**Comment by tkoyama010** [comment]
PR travis for sphinx translation always fails 🐧

**Comment by cocoatomo** [comment]
Thank you for the PR.

I am responsible for the failure of Travis ci build.
Please wait for some days.

**Comment by cocoatomo** [comment]
I fixed!

**Comment by cocoatomo** [comment]
Sorry, but this repository is not yet ready for PR building.
I approve of this PR.

**Pull request merged**
